name: .NET

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKDIR: "./src/Helloworld"
      CONFIG: "Release"
      AZURE_FUNCTIONAPP_NAME: "func3"
      AZURE_FUNCTIONAPP_PACKAGE_PATH: "${{env.WORKDIR}}/bin/Release/net6.0/publish/"
    defaults:
      run:
        working-directory: ${{env.WORKDIR}}

    steps:
    - name: "Checkout"
      uses: actions/checkout

    - name: Setup .NET Core SDK $
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ env.CONFIG }} --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish
      run: |
        dotnet publish -c ${{ env.CONFIG }}

    - name: 'Run Azure Functions action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
